# Generated by Django 6.0 on 2025-12-09 21:05

import fotos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0002_alter_photo_options_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=fotos.models.photo_upload_path, validators=[fotos.models.validate_image_size, fotos.models.validate_image_dimensions], verbose_name='Изображение'),
        ),
    ] 
